require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"

require "user.lsp"
require "user.autopairs"
require "user.nvim-tree"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.alpha"
require "user.autocommands"
require "user.stabilize"
require "user.lastplace"
require "user.preview"
require "user.todo-comments"
require "user.snippets"
require "user.dap"
require "user.navic"
require "user.winbar"

require "user.runner"
-- require "user.copilot"
--require "user.diffview"
-- require("user.cowboy").cowboy()

