require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
--require "user.telescope"
-- require "user.treesitter"
require "user.autopairs"
-- require "user.gitsigns"
require "user.nvim-tree"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
-- require "user.indentline"
require "user.alpha"
-- require "user.whichkey"
require "user.autocommands"
require "user.stabilize"
require "user.lastplace"
require "user.preview"
-- require "user.trouble"
-- require "user.neogen"
require "user.todo-comments"
-- require "user.quickscope"
-- require "user.matchup"
--require "user.numb"
-- require "user.lsp_signature"
-- require "user.comment"
-- require "user.surround"
require "user.outline"
require "user.snippets"
require "user.dap"
require "user.navic"
require "user.winbar"
-- require "user.illuminate"
-- require "user.colorizer"

require "user.runner"
require "user.diffview"

